filerooms/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf.urls import url, include
from . import views


room_patterns = [
    url(r'^$', views.RoomListView.as_view(), name='room-list'),
    url(r'^create/$', views.RoomCreateView.as_view(), name='room-create'),
    url(r'^(?P<slug>[\w-]+)/$', views.RoomDetailView.as_view(),
        name='room-detail'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.RoomDeleteView.as_view(),
        name='room-delete'),
    url(r'^(?P<slug>[\w-]+)/upload/$', views.DownloadCreateView.as_view(),
        name='download-create'),
    url(r'^(?P<room_slug>[\w-]+)/(?P<pk>\d+)/$',
        views.DownloadFileView.as_view(), name='download'),
    url(r'^(?P<room_slug>[\w-]+)/(?P<pk>\d+)/delete/$',
        views.DownloadDeleteView.as_view(), name='download-delete'),
]

# Enforce namespace here so url reverse work correctly
urlpatterns = (
    url(r'', include(room_patterns, namespace='filerooms')),
)

filerooms/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from . import abstract_models


class Room(abstract_models.AbstractRoom):
    pass


class Download(abstract_models.AbstractDownload):
    pass

filerooms/forms.py
from __future__ import unicode_literals, absolute_import

from django import forms
from django.db.models import get_model
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _


Room = get_model('filerooms', 'Room')
Download = get_model('filerooms', 'Download')


class RoomForm(forms.ModelForm):

    class Meta:
        model = Room
        fields = ('name', 'owners', 'is_public')

    def clean_name(self):
        name = self.cleaned_data['name']
        qs = Room.objects.all()
        if self.instance and self.instance.pk:
            # this is an update so we need to exclude existing
            qs = qs.exclude(pk=self.instance.pk)
        if qs.filter(slug=slugify(name)).exists():
            raise forms.ValidationError(
                _('a file room of this name already exists')
            )
        return name


class UploadForm(forms.ModelForm):

    def __init__(self, room, *args, **kwargs):
        super(UploadForm, self).__init__(*args, **kwargs)
        self.instance.room = room

    class Meta:
        model = Download
        fields = ('name', 'description', 'attachment')

filerooms/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.views import generic
from django.views.generic.detail import BaseDetailView
from django.db.models import get_model
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.utils.functional import cached_property

from braces import views
from sendfile import sendfile

from .forms import UploadForm, RoomForm


Room = get_model('filerooms', 'Room')
Download = get_model('filerooms', 'Download')


class CanAdministrateMixin(views.UserPassesTestMixin):

    def test_func(self, user):
        if user.is_superuser or user.is_staff:
            return True
        return False


class UserRoomMixin(object):

    model = Room

    def get_queryset(self):
        qs = super(UserRoomMixin, self).get_queryset()
        return qs.for_user(user=self.request.user)


class RoomListView(UserRoomMixin, views.LoginRequiredMixin,
                   generic.ListView):
    template_name = 'filerooms/room_list.html'
    context_object_name = 'rooms'
    paginate_by = 10


class RoomCreateView(UserRoomMixin, CanAdministrateMixin, generic.CreateView):
    template_name = 'filerooms/room_create.html'
    context_object_name = 'room'
    form_class = RoomForm
    success_url = reverse_lazy('filerooms:room-list')


class RoomDeleteView(UserRoomMixin, CanAdministrateMixin, generic.DeleteView):
    template_name = 'filerooms/room_confirm_delete.html'
    context_object_name = 'room'
    success_url = reverse_lazy("filerooms:room-list")


class UserDownloadsMixin(object):

    model = Download
    context_object_name = 'downloads'

    def get_queryset(self):
        qs = super(UserDownloadsMixin, self).get_queryset()
        return qs.for_user(user=self.request.user)


class GetRoomMixin(object):

    room_slug_field = 'slug'

    @cached_property
    def room(self):
        qs = Room.objects.for_user(self.request.user)
        return get_object_or_404(
            qs,
            slug=self.kwargs.get(self.room_slug_field, None))

    def get_context_data(self, **kwargs):
        ctx = super(GetRoomMixin, self).get_context_data(**kwargs)
        ctx['room'] = self.room
        return ctx


class RoomDetailView(UserDownloadsMixin, GetRoomMixin, generic.ListView):

    template_name = 'filerooms/room_detail.html'

    def get_queryset(self):
        qs = super(RoomDetailView, self).get_queryset()
        return qs.filter(room=self.room)


class DownloadFileView(UserDownloadsMixin,
                       BaseDetailView):

    def render_to_response(self, context):
        return sendfile(self.request, self.object.attachment.path,
                        attachment=True)


class DownloadCreateView(GetRoomMixin, CanAdministrateMixin,
                         generic.CreateView):
    model = Download
    template_name = 'filerooms/download_create.html'
    form_class = UploadForm

    def get_success_url(self):
        return reverse_lazy("filerooms:room-detail",
                            kwargs={'slug': self.room.slug})

    def get_form_kwargs(self):
        kwargs = super(DownloadCreateView, self).get_form_kwargs()
        kwargs['room'] = self.room
        return kwargs


class DownloadDeleteView(GetRoomMixin, CanAdministrateMixin,
                         generic.DeleteView):
    model = Download
    template_name = 'filerooms/download_confirm_delete.html'
    context_object_name = 'download'
    room_slug_field = 'room_slug'

    def get_success_url(self):
        return reverse_lazy("filerooms:room-detail",
                            kwargs={'slug': self.room.slug})

filerooms/templates/filerooms/base.html
<html>
    <body>
        <div>
            <h1>{% block heading %}{% endblock heading %}</h1>
        </div>
        <hr/>
        <div>
            {% block content %}{% endblock content %}
        </div>
        <hr/>
        <div>
            {% block controls %}{% endblock controls %}
        </div>
    </body>
</html>

filerooms/templates/filerooms/download_confirm_delete.html
{% extends 'filerooms/base.html' %}
{% load i18n %}

{% block heading %}
    {% trans 'delete' %} {{ download.name }}
{% endblock heading %}

{% block content %}
    <p>{% trans 'Are you sure you want to delete' %} "{{ download.name }}"</p>
    <form method="post" action=".">
        {% csrf_token %}
        <a href="{% url 'filerooms:room-detail' room.slug %}">{% trans 'cancel' %}</a>
        <input type="submit" value="{% trans 'confirm'%}"  />
    </form>
{% endblock %}

filerooms/templates/filerooms/download_create.html
{% extends 'filerooms/base.html' %}
{% load i18n %}

{% block heading %}
    {% trans 'create a new download in' %} {{ room.name }}
{% endblock heading %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'filerooms:room-list' %}">{% trans 'cancel' %}</a>
        <input type="submit" value="{% trans 'confirm'%}"  />
    </form>
{% endblock %}

filerooms/templates/filerooms/download_list.html
{% extends 'filerooms/base.html' %}
{% load i18n %}

{% block heading %}
    {{ room.name }}
{% endblock heading %}

{% block content %}

    <table>
        <thead>
            <tr>
                <th>{% trans 'file name' %}</th>
                <th>{% trans 'description' %}</th>
                <th>{% trans 'size' %}</th>
                <th></th>
            </th>
        </thead>
        <tbody>
        {% for download in downloads %}
            <tr>
                <td> {{ download.name }} </td>
                <td> {{ download.description }} </td>
                <td> {{ download.size|filesizeformat }} </td>
                <td>
                    <a href="{{ download.get_absolute_url }}">{% trans 'download' %}</a>
                    {% if user.is_staff or user.is_superuser %}
                        - <a href="{% url 'filerooms:download-delete' room.slug download.pk %}">{% trans 'delete' %}</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}
{% block controls %}
{% if user.is_staff or user.is_superuser %}
    <a href="{% url 'filerooms:download-create' room.slug %}">Upload a new file</a>
{% endif %}
{% endblock controls %}

filerooms/templates/filerooms/room_confirm_delete.html
{% extends 'filerooms/base.html' %}
{% load i18n %}

{% block heading %}
    {% trans 'delete' %} {{ room.name }}
{% endblock heading %}

{% block content %}
    <p>
        {% blocktrans %}Are you sure you want to delete "{{ room.name }}" and all it's contents?{% endblocktrans %}
    </p>
    <form method="post" action=".">
        {% csrf_token %}
        <a href="{% url 'filerooms:room-list' %}">{% trans 'cancel' %}</a>
        <input type="submit" value="{% trans 'confirm'%}"  />
    </form>
{% endblock %}

filerooms/templates/filerooms/room_create.html
{% extends 'filerooms/base.html' %}
{% load i18n %}

{% block heading %}
    {% trans 'create a new file room' %}
{% endblock heading %}

{% block content %}
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'filerooms:room-list' %}">{% trans 'cancel' %}</a>
        <input type="submit" value="{% trans 'confirm'%}"  />
    </form>
{% endblock %}

filerooms/templates/filerooms/room_list.html
{% extends 'filerooms/base.html' %}
{% load i18n %}

{% block heading %}
    {% trans 'file rooms' %}
{% endblock heading %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>{% trans 'name' %}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for room in rooms %}
            <tr>
                <td>{{ room.name }}</td>
                <td>
                    <a href="{{ room.get_absolute_url }}">{% trans 'open' %}</a>
                    {% if user.is_staff or user.is_superuser %}
                         - <a href="{% url  'filerooms:room-delete' room.slug %}">delete</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block controls %}
{% if user.is_staff or user.is_superuser %}
    <a href="{% url 'filerooms:room-create' %}">{% trans 'create a new file room' %}</a>
{% endif %}
{% endblock controls %}